/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        "error-container": "#fe8983",
        "on-secondary": "#f5f9ff",
        "tertiary-dim": "#54543e",
        background: "#f9f9f7",
        "on-primary": "#f9f7f7",
        "tertiary-fixed": "#f7f5d7",
        error: "#9f403d",
        "inverse-primary": "#ffffff",
        "secondary-dim": "#415566",
        "error-dim": "#4e0309",
        "on-primary-container": "#515252",
        "tertiary-fixed-dim": "#e9e7ca",
        "surface-container": "#ecefec",
        "on-secondary-container": "#3f5465",
        "on-secondary-fixed": "#2d4251",
        "primary-fixed": "#e4e2e2",
        "primary-container": "#e4e2e2",
        "on-surface": "#2d3432",
        "on-tertiary-fixed": "#4b4b35",
        "primary-fixed-dim": "#d5d4d4",
        secondary: "#4d6172",
        "on-primary-fixed": "#3f3f3f",
        "surface-dim": "#d4dcd8",
        "on-tertiary": "#fdfadd",
        "on-background": "#2d3432",
        surface: "#f9f9f7",
        "on-error": "#fff7f6",
        "secondary-fixed-dim": "#c1d7eb",
        "surface-container-highest": "#dee4e0",
        "on-surface-variant": "#5a605e",
        "inverse-on-surface": "#9c9d9b",
        "primary-dim": "#525252",
        "on-error-container": "#752121",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#495e6f",
        "surface-bright": "#f9f9f7",
        "secondary-fixed": "#cfe5f9",
        "on-primary-fixed-variant": "#5b5b5b",
        "surface-tint": "#5e5e5e",
        "on-tertiary-fixed-variant": "#686750",
        "inverse-surface": "#0d0f0e",
        "surface-container-low": "#f2f4f2",
        "tertiary-container": "#f7f5d7",
        "outline-variant": "#adb3b0",
        tertiary: "#616049",
        "secondary-container": "#cfe5f9",
        "surface-variant": "#dee4e0",
        outline: "#767c79",
        "surface-container-high": "#e5e9e6",
        primary: "#5e5e5e",
        "on-tertiary-container": "#5d5d46",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        manrope: ["Manrope", "sans-serif"],
      },
      boxShadow: {
        glass: "0 12px 40px rgba(45,52,50,0.06)",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
